apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: influx
  name: influxdb
spec:
  replicas: 1
  selector:
    name: influx
  template:
    metadata:
      labels:
        name: influx
    spec:
      containers:
      - name: influxdb
        image: index.caicloud.io/caicloud/influxdb:1.0.0-beta2
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}
